name: Promote Release Version
on:
  push:
    paths:
    - 'version.properties'

jobs:
  promote-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Set Release Version
        run: echo "VERSION=`./bin/buildinfo.py long`" >> $GITHUB_ENV
      - name: Print Release Version
        run: echo "Setting release version ${{ env.VERSION }}"
      - name: Create Release Tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{env.VERSION}}",
              sha: context.sha
            })
